### PR TITLE
Fix multiline comment spacing on TOML configs

### PR DESCRIPTION
**Pull request by EnnuiL**
This PR fixes multiline comments on TOML not having the one space padding on their other lines

### CODE REVIEW

**Comment by Haven-King** [comment]
This is something that should probably be done in the annotation processor in QuiltConfig itself. I would also like to point at that you can use multiple `@Comment` annotations for multiline comments.

**Comment by TheGlitch76** [comment]
With multi-line strings in Java 17 it doesn't make sense to require splitting into multiple annotations

**Comment by Haven-King** [comment]
> With multi-line strings in Java 17 it doesn't make sense to require splitting into multiple annotations

Agreed, the functionality in this PR makes sense. I just thought it was worth mentioning that there is an existing solution for multiline comments.

**Comment by EnnuiL** [comment]
Yeah, I made this PR so that `@Comment` played nicer with Java's multiline strings; I did strumble on the possibility of using multiple `@Comment` while making this PR, but yeah, I prefer the triple double-quotes

**Comment by Haven-King** [comment]
https://github.com/QuiltMC/quilt-config/pull/3 succeeds this pull request.

**Pull request closed without merging**
