### PR TITLE
feat(loader): cli parameter to ignore unknown mods

### LINKED ISSUE #433: Skip unknown mods windows
Is there a way to skip the windown shown when there're files that are not mods? The `.dll` file just needs to be there :smile: 

image

### PR DESCRIPTION
**Pull request by voidpointer0x00**
Fixes #433 restoring old behavior _(not shore which version this GUI was introduced in)_ with extra cli argument `--ignore-unknown-mods`

### CODE REVIEW

**Review by AlexIIL — CHANGES_REQUESTED** [review]
Thanks for the PR! I agree that this is needed, but not quite with how this is implemented.

Specifically:
1. Quilt-loader generally uses system properties to configure its behavior - these are the static constants in [`SystemProperties`](https://github.com/QuiltMC/quilt-loader/blob/develop/src/main/java/org/quiltmc/loader/impl/util/SystemProperties.java). Can you replace the argument with a system property like `loader.ignore_unsupported_mods`? (This also means we don't pass it to minecraft, which logs a message like `Completely ignored arguments: [--ignore-unknown-mods]`)
2. I think this is the wrong place to filter out ignored mods - the window which gets hidden *could* contain unrelated warnings (in the `Files` tab) which should still be shown if the config option `always_show_mod_state_window` is enabled. Instead, this should probably go in `QuiltPluginManagerImpl.populateModsGuiTab` (where the warnings are generated) - basically just skip the unsupported mod checking if the system property is set to true.

**Comment by voidpointer0x00** [comment]
@AlexIIL, thanks for the review, will redo :)

**Comment by voidpointer0x00** [comment]
@AlexIIL, reimplemented, tested — that also works

**Review by AlexIIL — APPROVED** [review]

**Comment by AlexIIL** [comment]
Thanks!

**Pull request merged**
